### ISSUE TITLE
ModuleNotFoundError: No module named 'medl'

### ISSUE THREAD

**Issue by CAPTAIN320** [NVIDIA/clara-train-examples#11]
Anytime I try doing something related to training, I get this error: 

`Error while finding module specification for 'medl.apps.train' (ModuleNotFoundError: No module named 'medl')`

I tried searching everywhere, but there is no python module for medl.

Please help!!!

**Comment by CAPTAIN320** [comment]
Hello! I did solve it. What I tried doing is to run the docker container version of Clara as per the documentation.
A jupyter notebook page will open. You then use the CLI found within this notebook environment to run the Clara commands.

**Comment by CAPTAIN320** [comment]
> Hi, @CAPTAIN320! Have you resolved this problem? If so, what helped you? I faced this error trying to run Clara FL on MMAR. I can't find any references to medl. I guess it is an internal Clara module, but I have no idea how to deal with it or there are any workarounds.

Hello! I did solve it. What I tried doing is to run the docker container version of Clara as per the documentation.
A jupyter notebook page will open. You then use the CLI found within this notebook environment to run the Clara commands.

**Comment by katerina-merkulova** [comment]
> > Hi, @CAPTAIN320! Have you resolved this problem? If so, what helped you? I faced this error trying to run Clara FL on MMAR. I can't find any references to medl. I guess it is an internal Clara module, but I have no idea how to deal with it or there are any workarounds.
> 
> Hello! I did solve it. What I tried doing is to run the docker container version of Clara as per the documentation. A jupyter notebook page will open. You then use the CLI found within this notebook environment to run the Clara commands.

Oh, Thank you so much! 😊
