### ISSUE TITLE
models folder not created

### ISSUE THREAD

**Issue by LSnyd** [NVIDIA/clara-train-examples#6]
Hi there, 

I just tried to get the GettingStarted notebook running, but I kept getting the following Error, when running the train_W_Config.sh file

`mkdir: cannot create directory ‘/home/lisa/projects/clara-train-examples/PyTorch/NoteBooks/GettingStarted/commands/../models/config_train_Unet’: No such file or director`

I believe this occurs, since the models folder is not created before the config_train_Unet folder is created. 
It worked after I manually added the models folder in the GettingStarted directory. 

Best,
Lisa

**Comment by Minxiangliu** [comment]
@LSnyd 
Hi, I also use your method to solve this problem.
In addition, did you successfully load `Tensorboard` when you ran in GettingStarted notebook?
After I trained this example, I couldn’t use `Tensorboard` to load the log file in the `models/config_train_Unet/log...`.
It show not found data! Actually, the log file is exist.
This confuses me.

**Comment by LSnyd** [comment]
Hi @Minxiangliu, 
I also couldn't figure out how to get Tensorboard running :( 

 I couldn't even find the tensor board log files. I thought the .log files in the models folder are rather the logs of the terminal than tensorboard logs? Don't tensorboard log files always have an 'event.out' prefix in it?

**Comment by Minxiangliu** [comment]
Hi @LSnyd ,
You can get `Tensorboard` running in picture below.
![image](https://user-images.githubusercontent.com/30144428/121102498-46fe7a00-c830-11eb-8584-b3ea19e460b3.png)

My log directory is as follows, I even use [Tensorboard](https://github.com/tensorflow/tensorboard/blob/master/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong) for debugging.
![image](https://user-images.githubusercontent.com/30144428/121103143-cccef500-c831-11eb-962c-9e0a4b95a287.png)

```
root@c7c2d5597eb8:/claraDevDay/GettingStarted/models# find config_train_Unet/ | grep tfevents
config_train_Unet/events.out.tfevents.1623057976.c7c2d5597eb8.410.0
root@c7c2d5597eb8:/claraDevDay/GettingStarted/models# tensorboard --inspect --logdir config_train_Unet/
TensorFlow installation not found - running with reduced feature set.
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
config_train_Unet/

These tags are in config_train_Unet/:
audio -
histograms -
images -
scalars
   train_acc
   train_loss
   val_acc
   val_mean_dice
tensor -
======================================================================

Event statistics for config_train_Unet/:
audio -
graph -
histograms -
images -
scalars
   first_step           1
   last_step            2
   max_step             8
   min_step             1
   num_steps            8
   outoforder_steps     [(4, 1), (8, 2)]
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```
So I don't know why `Tensorboard` did not find the data.
In addition, do you use `scripts/startClaraTrainNoteBooks.sh` or `scripts/startDocker.sh` for training? I’m using `startDocker.sh` for training, because `startClaraTrainNoteBooks.sh` can’t find the nvidia driver, I’m trying to clarify the problem.
Many thank!

**Comment by Minxiangliu** [comment]
OK.
I rewrite this line in `scripts/startDocker.sh`.
`extraFlag=${extraFlag}" -p "${jnotebookPort}":8888 -p "3031":5000 -p 6006:6006"`

Execute `tensorboard --logdir config_train_Unet` in the container, and successfully open `Tensorboard` with browser.
![image](https://user-images.githubusercontent.com/30144428/121110062-415c6080-c83f-11eb-8563-8cbec0a50e89.png)
Obviously there are still some bugs in v4.0.

**Comment by LSnyd** [comment]
Hi @Minxiangliu, 
thank you so much for your input! I couldn't find any tensorboard logs, since I accidentally started a Training that resulted in an Error beforehand. I could get Tensorboard running with your descriptions, thank you!

Regarding the bugs, it is probably best if we keep collecting them here on GitHub :)

**Comment by Minxiangliu** [comment]
Hi @LSnyd 
Can you tell me which script are you running? `scripts/startClaraTrainNoteBooks.sh` or `scripts/startDocker.sh`
Many thank!

**Comment by LSnyd** [comment]
I am running `scripts/startDocker.sh`
I haven't tried to get the other one running yet, but I will try it out in a second.

**Comment by Minxiangliu** [comment]
Hi @LSnyd 
If you want to run `scripts/startClaraTrainNoteBooks.sh` script and have nvidia driver, you can refer to this #7, I have done.

**Comment by LSnyd** [comment]
@Minxiangliu, wonderful thank you!
